spring.application.name=caches

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:cachedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console (accessible at /h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379